apiVersion: v2
name: firezone-relay
version: 0.18.0
appVersion: 709037bce5248589f6b7ab3f87ffc37e022e3b8e
type: application
description: A Helm chart for deploying a firezone relay
icon: https://raw.githubusercontent.com/firezone/firezone/main/website/public/images/logo-main.svg
