apiVersion: v2
name: firezone-relay
version: 0.53.0
# renovate-digest: datasource=custom.firezone-portal depName=portal
appVersion: a717ddb6d20588f282ba657293ed6a91b81ed252
type: application
description: A Helm chart for deploying a firezone relay
icon: https://raw.githubusercontent.com/firezone/firezone/main/website/public/images/logo-main.svg
