apiVersion: v2
name: firezone-relay
version: 0.20.0
appVersion: cb0bf44815fe51357b65c396eda6da34c85bb0bd
type: application
description: A Helm chart for deploying a firezone relay
icon: https://raw.githubusercontent.com/firezone/firezone/main/website/public/images/logo-main.svg
