apiVersion: v2
name: firezone-relay
version: 0.47.0
# renovate-digest: datasource=custom.firezone-portal depName=portal
appVersion: 208a5298db33c7bd7051211463e97924eb22dfa9
type: application
description: A Helm chart for deploying a firezone relay
icon: https://raw.githubusercontent.com/firezone/firezone/main/website/public/images/logo-main.svg
