image:
  repository: ghcr.io/firezone/relay
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

logLevel: trace
logFormat: json
config:
  # Websocket URL of the Firezone API
  apiUrl: wss://api.firezone.dev
  # Token provided to you by firezone
  # You can specify it directly of reference an existing secret
  # Note: It can also be a path to a file containing the token
  token:
    key: FIREZONE_TOKEN
    value:
    existingSecret:
  # The public IPv4 of the relay used by clients and gateways
  publicIPV4Addr:
  # The public IPv6 of the relay used by clients and gateways
  publicIPV6Addr:
  # The lowest port that can be used to relay traffic between clients and gateways
  TURNLowestPort: 49152
  # The highest port that can be used to relay traffic between clients and gateways
  TURNHighestPort: 65535
  # The port to listen on for STUN messages
  listenPort: 3478
  # Firezone relay supports OpenTelemetry for both traces and metrics.
  otlp:
    # Firezone relay only supports GRPC endpoint
    # Example value: localhost:4317
    endpoint:

revisionHistoryLimit: 10

envFrom: []
extraEnv: []

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  capabilities:
    add:
      - NET_ADMIN
    drop:
      - ALL
  readOnlyRootFilesystem: true

resources: {}

volumes: []

volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

dnsPolicy: ~
dnsConfig: {}

service:
  type: ClusterIP
  annotations: {}
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  externalTrafficPolicy: Local
  loadBalancerClass: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
