# yamllint disable rule:line-length
---
image:
  repository: us-east1-docker.pkg.dev/firezone-prod/firezone/relay
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

logLevel: trace
logFormat: human
config:
  apiUrl: wss://api.firezone.dev
  # Token provided to you by firezone
  token:
    secretName:
    key: FIREZONE_TOKEN
  # UUID used to identify the relay
  id:
    secretName:
    key: FIREZONE_ID
  TURNLowestPort: 49152
  TURNHighestPort: 65535

envFrom: []
extraEnv: []

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  allowPrivilegeEscalation: false
  capabilities:
    add:
      - NET_ADMIN
    drop:
      - ALL
  readOnlyRootFilesystem: true

resources: {}

volumes:
  - emptyDir: {}
    name: var-firezone

volumeMounts:
  - mountPath: /var/firezone
    name: var-firezone

nodeSelector: {}
tolerations: []
affinity: {}

service:
  type: ClusterIP
  annotations: {}
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
