---
variables:
  HELM_PROJECT: my-helm-project
  KUBERNETES_NAMESPACE: my-app-ns

stages:
  - generate
  - deploy

chart-generator:
  stage: generate
  image: alpine:3.19.0
  script:
    - ./.gitlab/generate-pipeline.sh > generated-pipeline.yml
  artifacts:
    expire_in: 1 hour
    paths:
      - generated-pipeline.yml

chart-jobs:
  stage: generate
  needs:
    - chart-generator
  trigger:
    include:
      - artifact: generated-pipeline.yml
        job: chart-generator
    strategy: depend
