apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "firezone.fullname" $) "api" }}
  labels:
    {{- include "firezone.api.labels" . | nindent 4 }}
    {{ .Values.firezone.erlangCluster.kubernetes.selector.key }}: {{ .Values.firezone.erlangCluster.kubernetes.selector.value }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 4369
      targetPort: epmd
      protocol: TCP
      name: epmd
    - port: {{ .Values.firezone.erlangCluster.distributionPort }}
      targetPort: distribution
      protocol: TCP
      name: distribution
  selector:
    {{- include "firezone.api.selectorLabels" . | nindent 4 }}
