apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "firezone.fullname" $) "api" }}
  labels:
    {{- include "firezone.api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.api.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "firezone.api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.api.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "firezone.api.labels" . | nindent 8 }}
        {{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "firezone.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "firezone.fullname" . }}
          env:
            - name: PHOENIX_HTTP_API_PORT
              value: {{ quote .Values.api.service.port }}
            - name: EXTERNAL_URL
              value: {{ required "Missing `firezone.externalApiURL`" .Values.global.externalApiURL }}
            - name: ERLANG_DISTRIBUTION_PORT
              value: {{ quote .Values.global.erlangCluster.distributionPort }}
            - name: RELEASE_NAME
              {{- if (and .Values.global.erlangCluster.enableKubernetesClusterModule (ne .Values.web.releaseName .Values.api.releaseName)) }}
              {{- required "api and web release names must be identical when using default kubernetes cluster module" "" }}
              {{- else }}
              value: {{ .Values.api.releaseName }}
              {{- end }}
            - name: RELEASE_HOSTNAME
              {{- if .Values.global.erlangCluster.enableKubernetesClusterModule }}
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
              {{- else }}
              value: {{ .Values.api.releaseHostname }}
              {{- end }}
            - name: RELEASE_COOKIE
              valueFrom:
                secretKeyRef:
                  name: {{ required "Missing `firezone.erlangCluster.cookie.secret`" .Values.global.erlangCluster.cookie.secret }}
                  key: {{ required "Missing `firezone.erlangCluster.cookie.key`" .Values.global.erlangCluster.cookie.key }}
            - name: OUTBOUND_EMAIL_ADAPTER_OPTS
              valueFrom:
                secretKeyRef:
                  name: {{ required "Missing `firezone.email.opts.secret`" .Values.global.email.opts.secret }}
                  key: {{ required "Missing `firezone.email.opts.key`" .Values.global.email.opts.key }}
            - name: BACKGROUND_JOBS_ENABLED
              value: {{ .Values.api.backgroundJobsEnabled | quote }}
            {{ include "firezone.database.auth" . | nindent 12 }}
            {{ include "firezone.secrets" . | nindent 12 }}
            {{- with .Values.api.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.global.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
            - name: epmd
              containerPort: {{ .Values.global.erlangCluster.epmdPort }}
              protocol: TCP
            - name: distribution
              containerPort: {{ .Values.global.erlangCluster.distributionPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          {{- with .Values.api.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.api.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
