{{- if .Values.migrations.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s" (include "firezone.fullname" $) "migrations" }}
  labels:
    {{- include "firezone.migrations.labels" . | nindent 4 }}
  {{- if .Values.migrations.annotations }}
  annotations:
    {{- with .Values.migrations.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  activeDeadlineSeconds: {{ .Values.migrations.activeDeadlineSeconds }}
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  template:
    metadata:
      annotations:
        {{- with .Values.migrations.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "firezone.migrations.labels" . | nindent 8 }}
        {{- with .Values.migrations.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: {{ .Values.migrations.restartPolicy }}
      {{- with .Values.migrations.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "firezone.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.migrations.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.migrations.securityContext | nindent 12 }}
          image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.migrations.image.pullPolicy }}
          args: 
            {{- toYaml .Values.migrations.args | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "firezone.fullname" . }}
          env:
            {{ include "firezone.common" . | nindent 12 }}
            {{ include "firezone.database.auth" . | nindent 12 }}
            {{ include "firezone.secrets" . | nindent 12 }}
            {{- with .Values.migrations.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.migrations.resources | nindent 12 }}
          {{- with .Values.migrations.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.migrations.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
