{{- if .Values.global.erlangCluster.enableKubernetesClusterModule -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "firezone.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "firezone.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "firezone.serviceAccountName" . }}
{{- end }}
