{{- if or (.Values.serviceAccount.create) (.Values.global.erlangCluster.enableKubernetesClusterModule) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "firezone.serviceAccountName" . }}
  labels:
    {{- include "firezone.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
