apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "firezone.fullname" $) "web" }}
  labels:
    {{- include "firezone.web.labels" . | nindent 4 }}
    {{ .Values.global.erlangCluster.kubernetes.selector.key }}: {{ .Values.global.erlangCluster.kubernetes.selector.value }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "firezone.web.selectorLabels" . | nindent 4 }}
