{{- if .Values.global.erlangCluster.enableKubernetesClusterModule -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "firezone.api.serviceAccountName" . }}
  labels:
    {{- include "firezone.api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "firezone.api.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "firezone.api.serviceAccountName" . }}
{{- end }}
