{{- if .Values.domain.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{  printf "%s-%s" (include "firezone.fullname" $) "domain" }}
  labels:
    {{- include "firezone.domain.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ printf "%s-%s" (include "firezone.fullname" $) "domain" }}
  minReplicas: {{ .Values.domain.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.domain.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.domain.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.domain.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.domain.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.domain.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
