{{- if .Values.domain.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "firezone.domain.fullname" . }}
  labels:
    {{- include "firezone.domain.labels" . | nindent 4 }}
    {{- with .Values.domain.pdb.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{ with .Values.domain.pdb.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.domain.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- else }}
  minAvailable: {{ .Values.domain.pdb.minAvailable | default 0 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "firezone.domain.selectorLabels" . | nindent 6 }}
{{- end }}
