{{- if .Values.global.erlangCluster.enableKubernetesClusterModule -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "firezone.domain.serviceAccountName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
{{- end }}
