apiVersion: v2
name: firezone
version: 0.53.0
# renovate-digest: datasource=custom.firezone-portal depName=portal
appVersion: 17dd6b7282a7d26dc90a716a68a63210b59887a5
type: application
description: A Helm chart for deploying firezone
icon: https://raw.githubusercontent.com/firezone/firezone/main/website/public/images/logo-main.svg
