apiVersion: v2
name: firezone
version: 0.51.0
# renovate-digest: datasource=custom.firezone-portal depName=portal
appVersion: 37f1322178ce76ddc879ee721725f9dd340c071f
type: application
description: A Helm chart for deploying firezone
icon: https://raw.githubusercontent.com/firezone/firezone/main/website/public/images/logo-main.svg
