apiVersion: v2
name: firezone
version: 0.16.0
appVersion: 5888aa0f49fa1e52d3ba570d9ab024b1a914db8c
type: application
description: A Helm chart for deploying firezone
icon: https://raw.githubusercontent.com/firezone/firezone/main/website/public/images/logo-main.svg
