apiVersion: v2
name: firezone
version: 0.35.0
# renovate-digest: datasource=custom.firezone-portal depName=portal
appVersion: 1fdfe7f3726206d43e142e16b6208310e98d7181
type: application
description: A Helm chart for deploying firezone
icon: https://raw.githubusercontent.com/firezone/firezone/main/website/public/images/logo-main.svg
