{{- if .Values.global.erlangCluster.enableKubernetesClusterModule -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "firezone.web.serviceAccountName" . }}
  labels:
    {{- include "firezone.web.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
{{- end }}
