apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firezone-relay.fullname" . }}
  labels:
    {{- include "firezone-relay.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "firezone-relay.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "firezone-relay.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "firezone-relay.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          env:
            - name: FIREZONE_API_URL
              value: {{ .Values.config.apiUrl }}
            - name: FIREZONE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: FIREZONE_TOKEN
              valueFrom:
                secretKeyRef:
                  {{- if .Values.config.token.existingSecret }}
                  name: {{ .Values.config.token.existingSecret  }}
                  {{- else }}
                  name: {{ include "firezone-relay.fullname" . }}
                  {{- end }}
                  key: {{ .Values.config.token.key }}
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
            - name: LOG_FORMAT
              value: {{ .Values.logFormat }}
            - name: LISTEN_PORT
              value: {{ quote .Values.config.listenPort }}
            - name: LOWEST_PORT
              value: {{ quote .Values.config.TURNLowestPort }}
            - name: HIGHEST_PORT
              value: {{ quote .Values.config.TURNHighestPort }}
            {{- if .Values.config.publicIPV4Addr }}
            - name: PUBLIC_IP4_ADDR
              value: {{ quote .Values.config.publicIPV4Addr }}
            {{- end }}
            {{- if .Values.config.publicIPV6Addr }}
            - name: PUBLIC_IP6_ADDR
              value: {{ quote .Values.config.publicIPV6Addr }}
            {{- end }}
            {{- if .Values.config.otlp.endpoint }}
            - name: OTLP_GRPC_ENDPOINT
              value: {{ quote .Values.config.otlp.endpoint }}
            {{- end }}
            - name: HEALTH_CHECK_ADDR
              value: 0.0.0.0:9000
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: stun
              containerPort: {{ .Values.config.listenPort }}
              protocol: UDP
            - name: health
              containerPort: 9000
              protocol: TCP
          {{- range $index, $port := (untilStep (int .Values.config.TURNLowestPort) (int (add (.Values.config.TURNHighestPort) 1)) 1) }}
            - name: turn-{{ $index }}
              containerPort: {{ $port }}
              protocol: UDP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          readinessProbe:
            httpGet:
              path: /healthz
              port: health
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
