{{- if not .Values.config.token.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firezone-relay.fullname" . }}
  labels:
    {{- include "firezone-relay.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.config.token.key }}: {{ .Values.config.token.value | b64enc | quote }}
{{- end }}
