apiVersion: v1
kind: Service
metadata:
  name: {{ include "firezone-relay.fullname" . }}
  labels:
    {{- include "firezone-relay.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - name: stun
      port: 3478
      protocol: UDP
      targetPort: stun
  {{- range $index, $port := (untilStep (int .Values.config.TURNLowestPort) (int (add (.Values.config.TURNHighestPort) 1)) 1) }}
    - name: turn-{{ $index }}
      port: {{ $port }}
      protocol: UDP
      targetPort: turn-{{ $index }}
  {{- end }}
  selector:
    {{- include "firezone-relay.selectorLabels" . | nindent 4 }}
